services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://localhost:5000
    ports:
      - "3000:8080"
    develop:
      watch:
        - action: rebuild
          path: ./frontend/src
        - action: rebuild
          path: ./frontend/package.json
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - PORT=5000
      - QURAN_API_BASE_URL=https://api.alquran.cloud/v1/ayah
    ports:
      - "5000:5000"
    develop:
      watch:
        - action: rebuild
          path: ./backend/src
        - action: rebuild
          path: ./backend/package.json
    networks:
      - app-network

networks:
  app-network:
    driver: bridge